/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SEED = 2b01
*/
module prng2_10 (
    input clk,
    input rst,
    input next,
    output reg [1:0] number,
    output reg prngdone
  );
  
  localparam SEED = 2'h1;
  
  
  reg [1:0] M_out_d, M_out_q = 1'h0;
  reg M_done_d, M_done_q = 1'h0;
  
  reg temp;
  
  reg [1:0] temp_out;
  
  always @* begin
    M_done_d = M_done_q;
    M_out_d = M_out_q;
    
    prngdone = M_done_q;
    number = M_out_q;
    if (next == 1'h1 & ~M_done_q) begin
      temp = M_out_q[0+0-:1] ^ M_out_q[1+0-:1];
      temp_out = M_out_q >> 1'h1;
      temp_out[1+0-:1] = temp;
      M_out_d = temp_out;
      M_done_d = 1'h1;
    end else begin
      if (next == 1'h0) begin
        M_done_d = 1'h0;
      end
    end
    if (rst) begin
      M_out_d = 2'h1;
      M_done_d = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    M_out_q <= M_out_d;
    M_done_q <= M_done_d;
  end
  
endmodule
