/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module convertALUFN_6 (
    input clk,
    input rst,
    input [1:0] oper,
    output reg [5:0] alufn
  );
  
  
  
  always @* begin
    
    case (oper)
      1'h0: begin
        alufn = 6'h00;
      end
      1'h1: begin
        alufn = 6'h01;
      end
      2'h2: begin
        alufn = 6'h02;
      end
      2'h3: begin
        alufn = 6'h09;
      end
      default: begin
        alufn = 6'h00;
      end
    endcase
  end
endmodule
