/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module ledMatrix_17 (
    input clk,
    input rst,
    input [4:0] digit,
    output reg [4:0] ledx,
    output reg [7:0] ledy,
    input [2:0] cycle
  );
  
  
  
  
  always @* begin
    ledx = 5'h00;
    ledy = 8'h00;
    
    case (digit)
      5'h00: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h06;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h09;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h09;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h09;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h09;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h06;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h01: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h02;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h06;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h02;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h02;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h02;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h07;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h02: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h07;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h09;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h01;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h0f;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h08;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h0f;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h03: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h0f;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h01;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h0f;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h01;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h01;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h0f;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h04: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h09;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h09;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h0f;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h01;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h01;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h01;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h05: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h0f;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h08;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h0f;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h01;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h01;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h0f;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h06: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h0f;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h08;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h0f;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h09;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h09;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h0f;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h07: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h0f;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h01;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h02;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h04;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h04;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h04;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h08: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h0f;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h09;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h0f;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h09;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h09;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h0f;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h09: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h0f;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h09;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h0f;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h01;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h01;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h01;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h0a: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h00;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h04;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h0e;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h04;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h00;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h00;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h0b: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h00;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h00;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h0f;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h00;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h00;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h00;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h0c: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h00;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h0a;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h04;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h0a;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h00;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h00;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h0d: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h04;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h00;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h0e;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h00;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h04;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h00;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h0e: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h00;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h0e;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h00;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h0e;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h00;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h00;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h0f: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h03;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h02;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h02;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h02;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h02;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h03;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h10: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h11;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h09;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h09;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h09;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h09;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h11;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h11: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h03;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h02;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h03;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h02;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h02;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h02;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h12: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h19;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h01;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h19;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h01;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h01;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h01;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h13: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h1c;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h00;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h1c;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h00;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h00;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h00;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h14: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h1e;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h12;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h06;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h04;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h00;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h04;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h15: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h07;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h05;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h07;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h04;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h04;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h04;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h16: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h08;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h08;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h0a;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h0a;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h0a;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h07;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h17: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h15;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h15;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h15;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h15;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h15;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h05;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h18: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h02;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h12;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h0a;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h0a;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h0a;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h06;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h19: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h1d;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h11;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h1d;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h05;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h04;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h1d;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
      5'h1a: begin
        
        case (cycle)
          3'h0: begin
            ledx = 5'h00;
            ledy = 8'h80;
          end
          3'h1: begin
            ledx = 5'h00;
            ledy = 8'h40;
          end
          3'h2: begin
            ledx = 5'h00;
            ledy = 8'h20;
          end
          3'h3: begin
            ledx = 5'h00;
            ledy = 8'h10;
          end
          3'h4: begin
            ledx = 5'h00;
            ledy = 8'h08;
          end
          3'h5: begin
            ledx = 5'h00;
            ledy = 8'h04;
          end
          3'h6: begin
            ledx = 5'h00;
            ledy = 8'h02;
          end
          3'h7: begin
            ledx = 5'h00;
            ledy = 8'h01;
          end
        endcase
      end
    endcase
  end
endmodule
